name: Bot Chiesa Automatico

on:
  # Orari automatici
  schedule:
    - cron: '0 6 * * *'      # Tutti i giorni ore 07:00 ITA
    - cron: '0 16 * * 6,0'   # Sabato e Domenica ore 17:00 ITA
  
  # Questo è il comando che fa apparire il pulsante!
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Scarica codice
        uses: actions/checkout@v3

      - name: 🐍 Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📚 Installa librerie
        run: pip install requests pandas matplotlib pillow

      - name: 🚀 Avvia il Bot
        env:
          FACEBOOK_TOKEN: ${{ secrets.FACEBOOK_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
