name: Bot Chiesa Anti Errore

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
    - cron: '0 16 * * 6,0'

# Ho spostato le password QUI IN ALTO così non sbagliamo gli spazi in fondo
env:
  FACEBOOK_TOKEN: ${{ secrets.FACEBOOK_TOKEN }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  avvia-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica Codice
        uses: actions/checkout@v3

      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa Librerie
        run: pip install requests pandas matplotlib pillow

      - name: Avvia Script
        run: python main.py
